<a href="https://colab.research.google.com/github/Rabin-246/Concepts-of-Technologies-and-AI/blob/main/workshop1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# To do

## Task 1 :

In [ ]:
import numpy as np

a = np.empty((2,2))
a


array([[4.66807966e-310, 0.00000000e+000],
       [            nan, 2.29175545e-312]])

In [ ]:
b = np.array([[1,2],[2,3],[4,5],[7,8]])
b

array([[1, 2],
       [2, 3],
       [4, 5],
       [7, 8]])

In [ ]:
import numpy as np
c = np.array([[2,54,6,7], [2,5,8,6]])
d = np.full(shape=(2,3), fill_value = 4)
d


array([[4, 4, 4],
       [4, 4, 4]])

In [ ]:
given_array = np.array([1,2,3,4])
new_array = np.zeros_like(given_array)
new_array


array([0, 0, 0, 0])

In [ ]:
given_array = np.array([[1,2,3],[3,4,5]])
new_array = np.ones_like(given_array)
new_array

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
new_list = [1,2,3,4]
c = np.array(new_list)
c

array([1, 2, 3, 4])

# Task 2 :

In [ ]:

new_array = np.arange(10,49,5, dtype=int)
new_array

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
A = ([[1,2,3], [4,5,6]])
new_matrix = np.reshape(A, (6,1))
new_matrix

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
a = ([[1,2,3],[2,3,4],[6,3,4]])
new_matrix = np.eye(3)
new_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
import numpy as np
a = np.random.random(30,)
a

array([0.92157873, 0.16485116, 0.471032  , 0.25880547, 0.46264141,
       0.32326096, 0.68335626, 0.63682626, 0.95736243, 0.17023107,
       0.56382566, 0.47564548, 0.59223552, 0.56760002, 0.23709884,
       0.01195362, 0.42578648, 0.09842601, 0.21537499, 0.37008534,
       0.97595155, 0.3878204 , 0.06220016, 0.16620788, 0.55326589,
       0.28322096, 0.35305356, 0.42818212, 0.79648068, 0.79160587])

In [ ]:
import numpy as np
arr = np.random.randint(100, size=(10,10))

min_value = np.min(arr)
max_value = np.max(arr)

print(arr)
print(min_value)
print(max_value)

[[57 15 99 24 89  6 93 44 37  0]
 [43 36 49 60 52 37  4 91 99 40]
 [99 36 48 50 26 97 65 19 68 67]
 [12 96 90 97 34 92 57 36 16 89]
 [42 22 57 38 99  2 35 70 90  6]
 [20 96 52 13 17 98 55 55 83 78]
 [31 32 89 11 31 40 72 63 53 81]
 [20 14  9 51  9 17 99 59  7 18]
 [62 46 81 10 18 50 37  4 82 49]
 [64 58 50 58 31 75 59 21 78 17]]
0
99


In [ ]:
arr = np.zeros(10);
print(arr);
arr[4] = 1;
print(arr);

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
arr = [1,2,0,0,4,0]
print(arr)
reversed_arr = arr[::-1]
print(reversed_arr)

[1, 2, 0, 0, 4, 0]
[0, 4, 0, 0, 2, 1]


In [ ]:
arr = np.zeros((3,4))
arr[0, :] = 1  # Top border
arr[-1, :] = 1  # Bottom border
arr[:, 0] = 1  # Left border
arr[:, -1] = 1  # Right border
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [ ]:
matrix = np.zeros((8,8))
matrix[1::2, ::2] = 1  # Fill 1s in odd rows, even columns
matrix[::2, 1::2] = 1  # Fill 1s in even rows, odd columns
print(matrix)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# Problem 3 :

 x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

 v = np.array([9,10]) and w = np.array([11,12]);
# 1. Add the two array.

In [ ]:
x = np.array([[1,2],[3,5]]);
y = np.array([[5,6],[7,8]]);
concat_matrix = np.concatenate((x,y), axis=0);
print(concat_matrix)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [ ]:
import numpy as np
v = np.array([9,10])
w = np.array([11,12]);
subtracted_matrix = np.subtract(w,v)
print(subtracted_matrix)

[2 2]


In [ ]:
x = np.array([[1,2],[3,5]]);
y = np.array([[5,6],[7,8]]);
new_matrix = np.multiply(x,y);
print(new_matrix)


[[ 5 12]
 [21 40]]


In [ ]:
result_1 = np.dot(x,y)
print("The dot product of matrix X and Y: ",result_1)
result_2 = np.dot(v,w)
print("The dot product of matrix V and W: ",result_2)
result_3 = np.dot(x,v)
print("The dot product of matrix X and V: ",result_3)

The dot product of matrix X and Y:  [[19 22]
 [50 58]]
The dot product of matrix V and W:  219
The dot product of matrix X and V:  [29 77]


In [ ]:
concat_along_row = np.concatenate([x,y], axis=1);
print("concatenated matrix is : ", concat_along_row)

# when we are using hstack or vstack we donot have to provide axis.
concat_along_row = np.hstack([x,y]);
print("Concatenate along horizontal or row using hstack: ",concat_along_row)

concat_along_column = np.concatenate([v,w], axis=0);
print("concatenated matrix is : ", concat_along_column)

concatenated matrix is :  [[1 2 5 6]
 [3 5 7 8]]
Concatenate along horizontal or row using hstack:  [[1 2 5 6]
 [3 5 7 8]]
concatenated matrix is :  [ 9 10 11 12]


In [ ]:
new_arr = np.concatenate([x,v])
print(new_arr)

# To concanate, all the input arrays must have same number of dimensions but the array  at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s).


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

# Task 4: Matrix Operations:

In [ ]:
A = np.array([[3,4],[7,8]]);
B = np.array([[5,3],[2,1]]);

inverse_matrix = np.linalg.inv(A)
dot_product = np.matmul(A,inverse_matrix)
print(dot_product)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
first_product = np.matmul(A,B)
print(first_product)
second_product = np.matmul(B,A)
print(second_product)

[[23 13]
 [51 29]]
[[36 44]
 [13 16]]


In [ ]:
product_1 = np.matmul(A,B)
AB_transpose = np.transpose(product_1)
print(AB_transpose)

B_transpose = np.transpose(B);
A_transpose = np.transpose(A)

B_transpose_multi_A_transpose = np.matmul(B_transpose,A_transpose)
print(B_transpose_multi_A_transpose)


[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


# Solve the following system of Linear equation using Inverse Methods.
 2x −3y+z =−1

 x −y+2z =−3

 3x +y−z =9

In [ ]:
F = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
G = np.array([[-1],[-3],[9]])

inverse_matrix_of_F = np.linalg.inv(F)

solution = np.dot(inverse_matrix_of_F,G)

print(inverse_matrix_of_F)
print("\nSolution (x, y, z):")
print(solution)


[[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution (x, y, z):
[[ 2.]
 [ 1.]
 [-2.]]
